### ISSUE TITLE
Get the full device name?

### ISSUE THREAD

**Issue by pickhardt** [GertjanReynaert/react-native-device#10]
Can I get the full device name, usually something like "John Smith's iPhone"?

I'd like to do something like this:

http://stackoverflow.com/a/21343625/3011531

So that I can get the user's full name from their device name.

**Comment by kkjdaniel** [comment]
#11 

Created a pull request updating the entire package to use the native UIDevice class, inside is a property that you can use to fetch the device name.

In the mean time you can use my [fork](https://github.com/kkjdaniel/react-native-device)
