### ISSUE TITLE
upgrade to v6

### ISSUE THREAD

**Issue by jawadrehman** [GertjanReynaert/react-native-device#4]
There seem to be a lot of issues I am facing whilst trying to upgrade to react-native 0.6.0-rc

Any help ? Thanks

**Comment by wootwoot1234** [comment]
There I've submitted a pull request  that fixes this bug.  You can read more about the fix here:
https://github.com/facebook/react-native/issues/1606

Here's the pull request that should fix the issue:
https://github.com/GertjanReynaert/react-native-device/pull/5

**Comment by GertjanReynaert** [comment]
Fixed in #9
