### ISSUE TITLE
Feature Device Orientation ?

### ISSUE THREAD

**Issue by DrMabuse23** [GertjanReynaert/react-native-device#7]
Hello thx for your module. Is it possible to add the device Orientation ?
thx

**Comment by GertjanReynaert** [comment]
Hm I would like to keep this package small and specific. Orientation isn't something that is easily integrated with my package, but you might want to take a look at https://www.npmjs.com/package/react-native-orientation.

**Comment by DrMabuse23** [comment]
i create my own thx for reply https://github.com/DrMabuse23/react-native-device-orientation
